export const itemsActionTypes = {
    ADD_ITEM_START: 'ADD_ITEM_START',
    ADD_ITEM_SUCCESS:'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE:'ADD_ITEM_FAILURE',

    FETCH_ITEMS_START: 'FETCH_ITEMS_START',
    FETCH_ITEMS_SUCCESS:'FETCH_ITEMS_SUCCESS',
    
    FETCH_ITEMS_FAILURE:'FETCH_ITEMS_FAILURE',

    TOGGLE_ITEM_PIN_START:'TOGGLE_ITEM_PIN_START',
    TOGGLE_ITEM_PIN_SUCCESS:'TOGGLE_ITEM_PIN_SUCCESS',
    TOGGLE_ITEM_PIN_FAILURE:'TOGGLE_ITEM_PIN_FAILURE',

    UPDATE_ITEM_START:'UPDATE_ITEM_START',
    UPDATE_ITEM_SUCCESS:'UPDATE_ITEM_SUCCESS',
    UPDATE_ITEM_FAILURE:'UPDATE_ITEM_FAILURE',

    COMPLETE_ITEM_START:'COMPLETE_ITEM_START',
    COMPLETE_ITEM_SUCCESS:'COMPLETE_ITEM_SUCCESS',
    COMPLETE_ITEM_FAILURE:'COMPLETE_ITEM_FAILURE',
    
    DELETE_ITEM_START:'DELETE_ITEM_START',
    DELETE_ITEM_SUCCESS:'DELETE_ITEM_SUCCESS',
    DELETE_ITEM_FAILURE:'DELETE_ITEM_FAILURE'
}