export const apisActionTypes = {
    FETCH_STOICISM_START:'FETCH_STOICISM_START', 
    FETCH_STOICISM_SUCCESS:'FETCH_STOICISM_SUCCESS', 
    FETCH_POEM_START:'FETCH_POEM_START', 
    FETCH_POEM_SUCCESS:'FETCH_POEM_SUCCESS', 
    FETCH_PHILOSOPHY_START:'FETCH_PHILOSOPHY_START', 
    FETCH_PHILOSOPHY_SUCCESS:'FETCH_PHILOSOPHY_SUCCESS', 
    FETCH_FAILURE:'FETCH_FAILURE'
}